### PR TITLE
Translated to zh_TW

### PR DESCRIPTION
**Pull request by coin3x**
Hope u and me also get pro version :)

### CODE REVIEW

**Comment by coin3x** [comment]
Closed for adding commits

**Comment by rypervenche** [comment]
Awesome job! I will go ahead and merge this.

**Comment by rypervenche** [comment]
Just a quick question. Where you translating from the English version or just fixing what was in my version of the files / using the variable names?

**Comment by coin3x** [comment]
Both. I didn't use the variable names

**Pull request merged**
